<h3>1. Numpy Datatype</h3><hr/>
<ul> 
    <li> array 내의 데이터 타입은 숫자, 문자, boolean 모두 가능
    <li> 그러나 특정 array 내의 데이터타입은 모두 동일해야 한다.
    <li>만약 서로 다른 경우 임의로 강제 변환시킴
</ul>
<br> (str > float > int 순)

In [3]:
import numpy as np

array = np.array([1, '2', True])
print(array)

['1' '2' 'True']


대량의 Dataset 을 다룰 때는 astype 함수를 사용하여 float > int 로 변환하도록 한다.

In [14]:
array= np.array([1.0, 2.0, 3.0])
array.astype(np.int32)

array([1, 2, 3])

<h3> 2. Axis 의 차원 관련 </h3><hr/>

직관적으로 axis0 - axis1 - axis2... 로 <u>0부터 고차원이라고 생각</u><br>
비쥬얼적으로, <b style = "color: blue; font-size: 20px;"> 제일 나중에 오는 axis가 열방향 (열의 개수) </b>
<b style = "color:red; font-size: 20px;"> 그다음 axis 가 행방향 (행의 개수) </b>
이후로는 ...

<h3> 3. reshape(-1) 의 의미 </h3><hr/>
reshape(-1, ....) 는 해당 위치의 axis 는 다른 차원 참조하여 "알아서 잘 배열" 의 의미임 <br/>
주로,<br/>
reshape(-1, 1) : 1차원 배열 -> 2차원의 벡터 형태로 (행 n개 / 열 1개)<br/>
reshape(-1, ) : 2차원 배열 -> 1차원의 열 형태로 (행 1개 / 열 n개)<br/>

In [6]:
import numpy as np

array1d = np.array([1,2,3,4,5])
print(array1d.reshape(-1, 1))

array2d = np.array([[1], [2], [3], [4], [5]])
print(array2d.reshape(-1, ))

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]


-1은 꼭 최상위 차원뿐 아니라 다른 차원에서도 역할 가능<br>
다만 딱 한 차원만 random 하게 설정 가능 (어찌보면 당연한...)<br>
-> ValueError: can only specify one unknown dimension

In [12]:
array = np.arange(8)
array3d = array.reshape(2,2,2)

#1차원을 2차원 / 알아서로 변환

array1 = array.reshape(-1, 4) ## array.reshape(2, 4) 와 동일
print(array1)
array2 = array.reshape(4, -1)  ## array.reshape(4, 2) 와 동일
print(array2)

# 3차원을 2차원으로 변환

array3 = array3d.reshape(-1, 1)
print(array3)

# 1차원을 2차원으로 변환

array4 = array.reshape(-1, 1)
print(array4)

# 3차원을 1차원으로 변환
array5 = array3d.reshape(-1, )
print(array5)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[0 1 2 3 4 5 6 7]
