<h3>1. Numpy Datatype</h3><hr/>
<ul> 
    <li> array 내의 데이터 타입은 숫자, 문자, boolean 모두 가능
    <li> 그러나 특정 array 내의 데이터타입은 모두 동일해야 한다.
    <li>만약 서로 다른 경우 임의로 강제 변환시킴
</ul>
<br> (str > float > int 순)

In [3]:
import numpy as np

array = np.array([1, '2', True])
print(array)

['1' '2' 'True']


대량의 Dataset 을 다룰 때는 astype 함수를 사용하여 float > int 로 변환하도록 한다.

In [14]:
array= np.array([1.0, 2.0, 3.0])
array.astype(np.int32)

array([1, 2, 3])

<h3> 2. Axis 의 차원 관련 </h3><hr/>

직관적으로 axis0 - axis1 - axis2... 로 <u>0부터 고차원이라고 생각</u><br>
비쥬얼적으로, <b style = "color: blue; font-size: 20px;"> 제일 나중에 오는 axis가 열방향 (열의 개수) </b>
<b style = "color:red; font-size: 20px;"> 그다음 axis 가 행방향 (행의 개수) </b>
이후로는 ...

<h3> 3. reshape(-1) 의 의미 </h3><hr/>
reshape(-1, ....) 는 해당 위치의 axis 는 다른 차원 참조하여 "알아서 잘 배열" 의 의미임 <br/>
주로,<br/>
reshape(-1, 1) : 1차원 배열 -> 2차원의 벡터 형태로 (행 n개 / 열 1개)<br/>
reshape(-1, ) : 2차원 배열 -> 1차원의 열 형태로 (행 1개 / 열 n개)<br/>

In [6]:
import numpy as np

array1d = np.array([1,2,3,4,5])
print(array1d.reshape(-1, 1))

array2d = np.array([[1], [2], [3], [4], [5]])
print(array2d.reshape(-1, ))

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]


-1은 꼭 최상위 차원뿐 아니라 다른 차원에서도 역할 가능<br>
다만 딱 한 차원만 random 하게 설정 가능 (어찌보면 당연한...)<br>
-> ValueError: can only specify one unknown dimension

In [12]:
array = np.arange(8)
array3d = array.reshape(2,2,2)

#1차원을 2차원 / 알아서로 변환

array1 = array.reshape(-1, 4) ## array.reshape(2, 4) 와 동일
print(array1)
array2 = array.reshape(4, -1)  ## array.reshape(4, 2) 와 동일
print(array2)

# 3차원을 2차원으로 변환

array3 = array3d.reshape(-1, 1)
print(array3)

# 1차원을 2차원으로 변환

array4 = array.reshape(-1, 1)
print(array4)

# 3차원을 1차원으로 변환
array5 = array3d.reshape(-1, )
print(array5)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[0 1 2 3 4 5 6 7]


<h3> 인덱싱 </h3>

<ul>
<li> 특정 위치의 단일값 추출
<li> 슬라이싱
<li> 팬시 인덱싱 -> 특정 위치들을 리스트나 ndarray로 반환하면 해당 위치들을 반환하는 방법 : array[[1,4,7]] = > array 에서 1, 4, 7번째 반환
<li> 불린 인덱싱 -> array([True, True, False, False, True]) => True 인 0, 1, 4번 반환
</ul>

In [9]:
import numpy as np
import pandas as pd

ar = np.arange(0, 9).reshape(3, -1)

print(ar[1:])
print(ar[1:, 1:2])


[[3 4 5]
 [6 7 8]]
[[4]
 [7]]


<h3>배열의 정렬 : sort()</h3>

np.sort(ndarray) : ndarray 는 그대로 둔 채 정렬 (inplace = False)
ndarray.sort() : ndarray 자체를 바꿔버리고 none 반환 (inplace = True)

params 에 오름차순, 내림차순이 없어서 내림차순으로 바꾸려면 : [::-1] 적용

In [28]:
ar = np.arange(0, 9).reshape(3, -1)

#1. 내림차순으로 변경
print(np.sort(ar)[::-1])

#2. axis 축 정렬
# 위에서 언급한대로 axis = 0 부터 고차원 ~~ 제일 마지막 axis 가 열방향

ar2d = np.array([[3, 7], [13, 5]])
print(np.sort(ar2d, axis = 0))
print(np.sort(ar2d, axis = 1))


[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[ 3  5]
 [13  7]]
[[ 3  7]
 [ 5 13]]


<h3>argsort()</h3>

정렬된 행렬의 원래 인덱스를 반환
정렬끼리 매핑할때 사용


In [33]:
ar = np.array([3, 1, 9, 5])

#1. argsort = > [1, 3, 5, 9] 로 변경
#2. 각각에 대응되어있던 원래 배열의 index  => [1, 0, 3, 2]
# return #2

sort_array = np.argsort(ar)
print(sort_array)

# 내림차순으로 정렬해도 [3, 2, 1, 0] 이 아니라 [9, 5, 3, 1] 정렬의 원래 배열의 indexing 반환

sort_desc = np.argsort(ar)[::-1]
print(sort_desc)


[1 0 3 2]
[2 3 0 1]


In [35]:
# 언제 쓰나? : 복수의 ndarray 가 매핑되는 순서로 나열되있는 가운데 특정 ndarray 를 기준으로 정렬하고 싶을때

name = np.array(['john', 'mike', 'sarah', 'kate'])
score = np.array([78, 95, 84, 98])

# 이때 "성적순" 으로 사람 정렬
sort_index = np.argsort(score)
print(sort_index)
print('성적 오름차순 순서를 name array 에 팬시인덱싱 : ', name[sort_index])

[0 2 1 3]
성적 오름차순 순서를 name array 에 팬시인덱싱 :  ['john' 'sarah' 'mike' 'kate']
