<h3>1. Numpy Datatype</h3><hr/>
<ul> 
    <li> array 내의 데이터 타입은 숫자, 문자, boolean 모두 가능
    <li> 그러나 특정 array 내의 데이터타입은 모두 동일해야 한다.
    <li>만약 서로 다른 경우 임의로 강제 변환시킴
</ul>
<br> (str > float > int 순)

In [50]:
import numpy as np

array = np.array([1, '2', True])
print(array)

['1' '2' 'True']


대량의 Dataset 을 다룰 때는 astype 함수를 사용하여 float > int 로 변환하도록 한다.

In [51]:
array= np.array([1.0, 2.0, 3.0])
array.astype(np.int32)

array([1, 2, 3])

<h3> 2. Axis 의 차원 관련 </h3><hr/>

직관적으로 axis0 - axis1 - axis2... 로 <u>0부터 고차원이라고 생각</u><br>
비쥬얼적으로, <b style = "color: blue; font-size: 20px;"> 제일 나중에 오는 axis가 열방향 (열의 개수) </b>
<b style = "color:red; font-size: 20px;"> 그다음 axis 가 행방향 (행의 개수) </b>
이후로는 ...

<h3> 3. reshape(-1) 의 의미 </h3><hr/>
reshape(-1, ....) 는 해당 위치의 axis 는 다른 차원 참조하여 "알아서 잘 배열" 의 의미임 <br/>
주로,<br/>
reshape(-1, 1) : 1차원 배열 -> 2차원의 벡터 형태로 (행 n개 / 열 1개)<br/>
reshape(-1, ) : 2차원 배열 -> 1차원의 열 형태로 (행 1개 / 열 n개)<br/>

In [52]:
import numpy as np

array1d = np.array([1,2,3,4,5])
print(array1d.reshape(-1, 1))

array2d = np.array([[1], [2], [3], [4], [5]])
print(array2d.reshape(-1, ))

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]


-1은 꼭 최상위 차원뿐 아니라 다른 차원에서도 역할 가능<br>
다만 딱 한 차원만 random 하게 설정 가능 (어찌보면 당연한...)<br>
-> ValueError: can only specify one unknown dimension

In [53]:
array = np.arange(8)
array3d = array.reshape(2,2,2)

#1차원을 2차원 / 알아서로 변환

array1 = array.reshape(-1, 4) ## array.reshape(2, 4) 와 동일
print(array1)
array2 = array.reshape(4, -1)  ## array.reshape(4, 2) 와 동일
print(array2)

# 3차원을 2차원으로 변환

array3 = array3d.reshape(-1, 1)
print(array3)

# 1차원을 2차원으로 변환

array4 = array.reshape(-1, 1)
print(array4)

# 3차원을 1차원으로 변환
array5 = array3d.reshape(-1, )
print(array5)

[[0 1 2 3]
 [4 5 6 7]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[0 1 2 3 4 5 6 7]


<h3> 인덱싱 </h3>

<ul>
<li> 특정 위치의 단일값 추출
<li> 슬라이싱
<li> 팬시 인덱싱 -> 특정 위치들을 리스트나 ndarray로 반환하면 해당 위치들을 반환하는 방법 : array[[1,4,7]] = > array 에서 1, 4, 7번째 반환
<li> 불린 인덱싱 -> array([True, True, False, False, True]) => True 인 0, 1, 4번 반환
</ul>

In [54]:
import numpy as np
import pandas as pd

ar = np.arange(0, 9).reshape(3, -1)

print(ar[1:])
print(ar[1:, 1:2])


[[3 4 5]
 [6 7 8]]
[[4]
 [7]]


<h3>배열의 정렬 : sort()</h3>

np.sort(ndarray) : ndarray 는 그대로 둔 채 정렬 (inplace = False)
ndarray.sort() : ndarray 자체를 바꿔버리고 none 반환 (inplace = True)

params 에 오름차순, 내림차순이 없어서 내림차순으로 바꾸려면 : [::-1] 적용

In [55]:
ar = np.arange(0, 9).reshape(3, -1)

#1. 내림차순으로 변경
print(np.sort(ar)[::-1])

#2. axis 축 정렬
# 위에서 언급한대로 axis = 0 부터 고차원 ~~ 제일 마지막 axis 가 열방향

ar2d = np.array([[3, 7], [13, 5]])
print(np.sort(ar2d, axis = 0))
print(np.sort(ar2d, axis = 1))


[[6 7 8]
 [3 4 5]
 [0 1 2]]
[[ 3  5]
 [13  7]]
[[ 3  7]
 [ 5 13]]


<h3>argsort()</h3>

정렬된 행렬의 원래 인덱스를 반환
정렬끼리 매핑할때 사용


In [56]:
ar = np.array([3, 1, 9, 5])

#1. argsort = > [1, 3, 5, 9] 로 변경
#2. 각각에 대응되어있던 원래 배열의 index  => [1, 0, 3, 2]
# return #2

sort_array = np.argsort(ar)
print(sort_array)

# 내림차순으로 정렬해도 [3, 2, 1, 0] 이 아니라 [9, 5, 3, 1] 정렬의 원래 배열의 indexing 반환

sort_desc = np.argsort(ar)[::-1]
print(sort_desc)


[1 0 3 2]
[2 3 0 1]


In [57]:
# 언제 쓰나? : 복수의 ndarray 가 매핑되는 순서로 나열되있는 가운데 특정 ndarray 를 기준으로 정렬하고 싶을때

name = np.array(['john', 'mike', 'sarah', 'kate'])
score = np.array([78, 95, 84, 98])

# 이때 "성적순" 으로 사람 정렬
sort_index = np.argsort(score)
print(sort_index)
print('성적 오름차순 순서를 name array 에 팬시인덱싱 : ', name[sort_index])

[0 2 1 3]
성적 오름차순 순서를 name array 에 팬시인덱싱 :  ['john' 'sarah' 'mike' 'kate']


In [58]:
import pandas as pd
titanic_df = pd.read_csv("./train.csv")

<h3> DataFrame 의 정보 -> .info() / .describe() </h3>

In [59]:
titanic_df.info()
titanic_df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

<h3> value_counts </h3>

1. value_counts 는 null값을 무시함 : dropna = False 로 셀 수 있음

2. series 에 대한 value_counts 할때는 bins parameter 를 활용해서 frequency table 만들 수 있음

3. 여러컬럼에 동시 count 하면 multiindex 생성함

In [60]:
titanic_df['Embarked'].value_counts(normalize = True)
titanic_df['Embarked'].value_counts(dropna= True)
titanic_df[['Embarked', 'Pclass']].value_counts()

Embarked  Pclass
S         3         353
          2         164
          1         127
C         1          85
Q         3          72
C         3          66
          2          17
Q         2           3
          1           2
dtype: int64

<h3> DataFrame, ndarray, 리스트, 딕셔너리 관계 </h3>

DataFrame - > ndarray : df.values
DataFrame - > 리스트 : df.values.tolist()
DataFrame -> 딕셔너리 : df.to_dict()

In [61]:
titanic_df.values
titanic_df.values.tolist()
titanic_df.to_dict()

{'PassengerId': {0: 1,
  1: 2,
  2: 3,
  3: 4,
  4: 5,
  5: 6,
  6: 7,
  7: 8,
  8: 9,
  9: 10,
  10: 11,
  11: 12,
  12: 13,
  13: 14,
  14: 15,
  15: 16,
  16: 17,
  17: 18,
  18: 19,
  19: 20,
  20: 21,
  21: 22,
  22: 23,
  23: 24,
  24: 25,
  25: 26,
  26: 27,
  27: 28,
  28: 29,
  29: 30,
  30: 31,
  31: 32,
  32: 33,
  33: 34,
  34: 35,
  35: 36,
  36: 37,
  37: 38,
  38: 39,
  39: 40,
  40: 41,
  41: 42,
  42: 43,
  43: 44,
  44: 45,
  45: 46,
  46: 47,
  47: 48,
  48: 49,
  49: 50,
  50: 51,
  51: 52,
  52: 53,
  53: 54,
  54: 55,
  55: 56,
  56: 57,
  57: 58,
  58: 59,
  59: 60,
  60: 61,
  61: 62,
  62: 63,
  63: 64,
  64: 65,
  65: 66,
  66: 67,
  67: 68,
  68: 69,
  69: 70,
  70: 71,
  71: 72,
  72: 73,
  73: 74,
  74: 75,
  75: 76,
  76: 77,
  77: 78,
  78: 79,
  79: 80,
  80: 81,
  81: 82,
  82: 83,
  83: 84,
  84: 85,
  85: 86,
  86: 87,
  87: 88,
  88: 89,
  89: 90,
  90: 91,
  91: 92,
  92: 93,
  93: 94,
  94: 95,
  95: 96,
  96: 97,
  97: 98,
  98: 99,
  99: 100,
  1

<h3> df_drop </h3>

In [67]:
# drop 은 index = []/ column = [] 에 대한 operation
# 만약 특정 행이나 열의 값에 기반한 drop 을 수행하고 싶으면
# boolean 화 해서 해당 boolean 을 index 나 column 에 간접적으로 적용하는 식으로 drop


# survived = 1인 행을 모두 드랍 (사망자만 추출)

titanic_df.drop(index = titanic_df.index.values[[titanic_df['Survived'] == 1]], axis = 0)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

<h3> DF 인덱싱 </h3>

1. 명칭기반 : df[['a', 'b', 'c'], ]

2. loc / iloc

3. boolean 인덱싱 : df[boolean 식] / 근데 df.loc[boolean식] 으로 해도 됨

4. 슬라이싱 : idx = pd.IndexSlice 선언 후 하기

In [73]:
idx = pd.IndexSlice

titanic_df.loc[idx[0:20], idx['Survived' : 'Age']]

Survived  Pclass                                               Name  \
0          0       3                            Braund, Mr. Owen Harris   
1          1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2          1       3                             Heikkinen, Miss. Laina   
3          1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4          0       3                           Allen, Mr. William Henry   
5          0       3                                   Moran, Mr. James   
6          0       1                            McCarthy, Mr. Timothy J   
7          0       3                     Palsson, Master. Gosta Leonard   
8          1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
9          1       2                Nasser, Mrs. Nicholas (Adele Achem)   
10         1       3                    Sandstrom, Miss. Marguerite Rut   
11         1       1                           Bonnell, Miss. Elizabeth   
12         0       3                     Saundercock, Mr. William Henry   
13         0       3                        Andersson, Mr. Anders Johan   
14         0       3               Vestrom, Miss. Hulda Amanda Adolfina   
15         1       2                   Hewlett, Mrs. (Mary D Kingcome)    
16         0       3                               Rice, Master. Eugene   
17         1       2                       Williams, Mr. Charles Eugene   
18         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...   
19         1       3                            Masselmani, Mrs. Fatima   
20         0       2                               Fynney, Mr. Joseph J   

       Sex   Age  
0     male  22.0  
1   female  38.0  
2   female  26.0  
3   female  35.0  
4     male  35.0  
5     male   NaN  
6     male  54.0  
7     male   2.0  
8   female  27.0  
9   female  14.0  
10  female   4.0  
11  female  58.0  
12    male  20.0  
13    male  39.0  
14  female  14.0  
15  female  55.0  
16    male   2.0  
17    male   NaN  
18  female  31.0  
19  female   NaN  
20    male  35.0

<h3>DataFrame [] 연산자의 특징</h3>

1. df['abc'] : df의 abc 컬럼에 해당하는 열을 <b style = "color:blue; font-size:20px"> 시리즈로 반환 </b>

2. df[['abc']] : df의 abc 컬럼에 해당하는 열을 <b style = "color:red; font-size:20px"> 데이터프레임으로 반환 </b>

필요에 따라서 사용할 것 (주료 df 로 사용하는게 각종 연산자 쓰기가...)

In [72]:
print(titanic_df['Survived'].info())

print(titanic_df[['Survived']].info())

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Survived
Non-Null Count  Dtype
--------------  -----
891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 1 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
dtypes: int64(1)
memory usage: 7.1 KB
None


<h3>Groupby 와 Aggregate</h3>

** Groupby 는 Grouping 된 별개의 객체들을 반환

해당 group은
grouped_list = df.groupby(by = ....) 에 대해서
개별 그룹들의 키 : grouped_list.groups.keys()
개별 그룹의 값 (=데이터프레임) : grouped_list.get_group(키값)
으로 실제 DataFrame 에 접근 가능


In [89]:
# 일반적인 Grouped 된 값들에 대해서는 group 전용 aggregate 함수를 사용하여 작업

grouped_df = titanic_df.groupby(by = ['Pclass'])

# 열별로 다른 함수 적용하려는 경우 아래 agg_dict = {'열명' : ['적용하려는 함수']....} 적용

agg_dict = {'Age' : [np.sum, np.mean], 'SibSp' : np.sum, 'Fare' : np.sum}
grouped_df.agg(agg_dict)


Age            SibSp        Fare
            sum       mean   sum         sum
Pclass                                      
1       7111.42  38.233441    90  18177.4125
2       5168.83  29.877630    74   3801.8417
3       8924.92  25.140620   302   6714.6951

In [87]:

# 모종의 이유로 각 Group 에 대해서 별도로 추가적인 작업이 필요하여 Group 을 이루고 있는 dataframe 자체에 접근하고 싶을수가 있음.

# grouped_df[['Age', 'PassengerId']].iloc[0] # -> 에러남. 직접 위치방식 접근은 불가



#1. 키값 식별

group_keys = grouped_df.groups.keys() # -> 각 그룹별로 할당된 키

#2. get_group 메서드로 불러오기

for i in group_keys:
    print(grouped_df.get_group(i))


     PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
6              7         0       1   
11            12         1       1   
23            24         1       1   
..           ...       ...     ...   
871          872         1       1   
872          873         0       1   
879          880         1       1   
887          888         1       1   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
23                        Sloper, Mr. William Thompson    male  28.0      0   
..                                                 ...     ...   ... 

<h3>isna 와 fillna 활용 </h3>

1. isna : 데이터 요소단위 (elememt-wise) 별로 na 인지 아닌지 판단해서 Boolean 반환

2. fillna : 한술 더 떠서 na 를 다른걸로 대체

In [90]:
titanic_df.isna()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

<h3> Isin 활용 </h3>

df.isin([a, b, ...] / {'컬렴명1': [a, b, c]..} / Dataframe)

df의 각 요소단위 (elementwise) 별로 isin 에서 지정한 iterable 내의 값이 하나라도 있는지 확인 => 있으면 True 반환

In [91]:
titanic_df.isin([0, 1])  # 1. 기준없이 그냥 df 내에 모든 요소중에 0 또는 1

titanic_df.isin({'Pclass' : [0, 1]}) # 2. df의 Pclass 컬럼 내의 요소중에 0, 1 또는 whatnot

titanic_df.isin(titanic_df[titanic_df['Sex'] == 'male']) 

# 3.df와 다른 df간 element-wise 로 비교하는데 이때 컬럼명과 인덱스명이 둘 다 같은 요소들만 비교



PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0           True      True    True   True   True   True   True   True    True   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4           True      True    True   True   True   True   True   True    True   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886         True      True    True   True   True   True   True   True    True   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False  False  False  False   False   
889         True      True    True   True   True   True   True   True    True   
890         True      True    True   True   True   True   True   True    True   

      Fare  Cabin  Embarked  
0     True  False      True  
1    False  False     False  
2    False  False     False  
3    False  False     False  
4     True  False      True  
..     ...    ...       ...  
886   True  False      True  
887  False  False     False  
888  False  False     False  
889   True   True      True  
890   True  False      True  

[891 rows x 12 columns]

<h3>nunique 로 고유값 파악 : 유니크한 값들이 몇개나 있는지 반환 </h3>

특정 컬럼의 고유값을 실제로 반환하고 싶으면

df['특정 컬럼'].unique()로 활용 

In [ ]:
titanic_df.nunique()

titanic_df['Name'].unique()

<h3> replace 활용 </h3>

1. 개별값 대체 : df.replace(a, b)

2. scalar 가 아닌 다른 형태도 전부 대체 가능

3. dict 구조 활용하여 컬럼별로 다르게 적용

4. (중요) regex 사용가능 : df.replace(re.compile, regex = True)

In [96]:
# 3번 dict 구조의 정수

# 이중 dict 로 : {열이름_1: {'기존값1' : '신규값1, 기존값2 : 신규값2...}, 열이름_2 : {기존값1:신규값1, ....}}

tdf = titanic_df.replace({'Survived' : {0 : 100, 1 : 200}, 'Sex' : {'male' : 'Man', 'female' : 'Woman'}}, inplace = False)

tdf


PassengerId  Survived  Pclass  \
0              1       100       3   
1              2       200       1   
2              3       200       3   
3              4       200       1   
4              5       100       3   
..           ...       ...     ...   
886          887       100       2   
887          888       200       1   
888          889       100       3   
889          890       200       1   
890          891       100       3   

                                                  Name    Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    Man  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  Woman  38.0      1   
2                               Heikkinen, Miss. Laina  Woman  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  Woman  35.0      1   
4                             Allen, Mr. William Henry    Man  35.0      0   
..                                                 ...    ...   ...    ...   
886                              Montvila, Rev. Juozas    Man  27.0      0   
887                       Graham, Miss. Margaret Edith  Woman  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  Woman   NaN      1   
889                              Behr, Mr. Karl Howell    Man  26.0      0   
890                                Dooley, Mr. Patrick    Man  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_cat  
0        0         A/5 21171   7.2500   NaN        S    Adult  
1        0          PC 17599  71.2833   C85        C    Adult  
2        0  STON/O2. 3101282   7.9250   NaN        S    Adult  
3        0            113803  53.1000  C123        S    Adult  
4        0            373450   8.0500   NaN        S    Adult  
..     ...               ...      ...   ...      ...      ...  
886      0            211536  13.0000   NaN        S    Adult  
887      0            112053  30.0000   B42        S    Adult  
888      2        W./C. 6607  23.4500   NaN        S  Elderly  
889      0            111369  30.0000  C148        C    Adult  
890      0            370376   7.7500   NaN        Q    Adult  

[891 rows x 13 columns]

apply lambda

엥간한건 알고.. 

1. if구문 다중조건 괄호

lambda x : 긍정결과 if x 조건이 참 else (긍정결과 if x 조건이 참 else 부정결과)

2. map (또는 df 에 대해서는 apply) 에 붙여서 사용

map(function , [iterable])
df.apply(function)

In [93]:
titanic_df['Age_cat'] = titanic_df['Age'].apply(lambda x : 'Child' if x <= 15 else ('Adult' if x <= 60 else 'Elderly'))
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Age_cat  
0        0         A/5 21171   7.2500   NaN        S    Adult  
1        0          PC 17599  71.2833   C85        C    Adult  
2        0  STON/O2. 3101282   7.9250   NaN        S    Adult  
3        0            113803  53.1000  C123        S    Adult  
4        0            373450   8.0500   NaN        S    Adult  
..     ...               ...      ...   ...      ...      ...  
886      0            211536  13.0000   NaN        S    Adult  
887      0            112053  30.0000   B42        S    Adult  
888      2        W./C. 6607  23.4500   NaN        S  Elderly  
889      0            111369  30.0000  C148        C    Adult  
890      0            370376   7.7500   NaN        Q    Adult  

[891 rows x 13 columns]